const ROTATING_CAROUSEL_INIT = '[rotating carousel] ROTATING_CAROUSEL_INIT'
const ROTATING_CAROUSEL_TOGGLE_INPUT =
  '[rotating carousel] ROTATING_CAROUSEL_TOGGLE_INPUT'
const ROTATING_CAROUSEL_FOCUS_INPUT =
  '[rotating carousel] ROTATING_CAROUSEL_FOCUS_INPUT'
const ROTATING_CAROUSEL_FOCUS_NEXT_INPUT =
  '[rotating carousel] ROTATING_CAROUSEL_FOCUS_NEXT_INPUT'
const ROTATING_CAROUSEL_FOCUS_PREV_INPUT =
  '[rotating carousel] ROTATING_CAROUSEL_FOCUS_PREV_INPUT'
const ROTATING_CAROUSEL_REMOVE_INPUT =
  '[rotating carousel] ROTATING_CAROUSEL_REMOVE_INPUT'

export const C = {
  ROTATING_CAROUSEL_INIT,
  ROTATING_CAROUSEL_TOGGLE_INPUT,
  ROTATING_CAROUSEL_FOCUS_INPUT,
  ROTATING_CAROUSEL_FOCUS_NEXT_INPUT,
  ROTATING_CAROUSEL_FOCUS_PREV_INPUT,
  ROTATING_CAROUSEL_REMOVE_INPUT,
}
